es_domain_name = "aula-es-domain"
es_ebs_enabled = true
es_ebs_volume_size = "10"
es_encryption_at_rest = false
es_instance_type = "t2.small.elasticsearch"
es_version = "6.4"
cloudwatch_es_index_slow_logs_group_name = "es/aula_es_index_slow_logs"
cloudwatch_es_search_slow_logs_group_name = "es/aula_es_search_slow_logs"
cloudwatch_es_application_logs_group_name = "es/aula_es_application_logs"
es_vpc_name = "aula-es-vpc"
es_vpc_cidr_block = "10.0.0.0/16"
es_vpc_azs = ["eu-central-1a", "eu-central-1b"]
es_vpc_private_subnets = ["10.0.1.0/24", "10.0.2.0/24"]
es_vpc_public_subnets = ["10.0.101.0/24", "10.0.102.0/24"]
es_sg_ingress_cidr_blocks = ["10.0.101.0/24", "10.0.102.0/24"]
es_sg_ingress_rules = ["elasticsearch-rest-tcp"]
es_sg_egress_cidr_blocks = ["0.0.0.0/0"]
es_sg_egress_rules = ["all-all"]